name = "rohith-portfolio"
main = "worker/src/index.js"
compatibility_date = "2025-01-01"

[assets]
directory = "./frontend"
binding = "ASSETS"
run_worker_first = ["/api/*"]

[[d1_databases]]
binding = "DB"
database_name = "portfolio-db"
database_id = "cd7e7ef2-a8c3-4a5e-a576-028770f1a11c"
migrations_dir = "database/migrations"
